//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoundSynchro
{
    using CodeFluent.Runtime;
    using CodeFluent.Runtime.Utilities;
    using System.Xml.Serialization;
    
    
    // CodeFluent Entities generated (http://www.softfluent.com). Date: .
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CodeFluent Entities", "1.0.01234.05678")]
    public enum MediaType
    {
        
        File = 0,
        
        Youtube = 1,
        
        SoundCloud = 2,
    }
}
