//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoundSynchro
{
    using CodeFluent.Runtime;
    using CodeFluent.Runtime.Utilities;
    using System.Xml.Serialization;
    
    
    // CodeFluent Entities generated (http://www.softfluent.com). Date: .
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CodeFluent Entities", "1.0.01234.05678")]
    public enum MediaType
    {
        
        File = 0,
        
        Youtube = 1,
        
        SoundCloud = 2,
        
        Deezer = 3,
    }
}
