//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoundSynchro
{
    using CodeFluent.Runtime;
    using CodeFluent.Runtime.Utilities;
    
    
    // CodeFluent Entities generated (http://www.softfluent.com). Date: Tuesday, 22 December 2015 14:46.
    // Build:1.0.61214.0832
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CodeFluent Entities", "1.0.61214.0832")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DataObjectAttribute()]
    [System.Diagnostics.DebuggerDisplayAttribute("Count={Count}")]
    [System.ComponentModel.TypeConverterAttribute(typeof(CodeFluent.Runtime.Design.CollectionTypeConverter))]
    public partial class MusicCollection : System.Collections.IList, System.Collections.ICollection, CodeFluent.Runtime.ICodeFluentSet, System.Collections.Generic.IList<SoundSynchro.Music>, System.Collections.Generic.ICollection<SoundSynchro.Music>, System.ComponentModel.IRaiseItemChangedEvents, System.ICloneable, System.ComponentModel.INotifyPropertyChanged, System.Collections.Specialized.INotifyCollectionChanged, System.ComponentModel.IBindingList, System.ComponentModel.ICancelAddNew
    {
        
        private bool _raisePropertyChangedEvents = true;
        
        private bool _raiseCollectionChangedEvents = true;
        
        [System.NonSerializedAttribute()]
        private System.Collections.Generic.List<SoundSynchro.Music> _baseList = new System.Collections.Generic.List<SoundSynchro.Music>();
        
        [System.NonSerializedAttribute()]
        private System.Collections.Generic.Dictionary<System.Guid, SoundSynchro.Music> _baseTable = new System.Collections.Generic.Dictionary<System.Guid, SoundSynchro.Music>();
        
        [System.NonSerializedAttribute()]
        private System.Collections.Hashtable _relations = new System.Collections.Hashtable();
        
        private int _maxCount = 2147483647;
        
        [System.NonSerializedAttribute()]
        private SoundSynchro.Playlist _musicsPlaylistPlaylist;
        
        [System.NonSerializedAttribute()]
        private int _addNewPos = -1;
        
        [System.NonSerializedAttribute()]
        private CodeFluent.Runtime.Utilities.BindingListManager<SoundSynchro.Music> _blm3642925835;
        
        private bool _raiseListChangedEvents = true;
        
        private System.Collections.Specialized.NotifyCollectionChangedEventHandler _h2943838991;

        event System.Collections.Specialized.NotifyCollectionChangedEventHandler System.Collections.Specialized.INotifyCollectionChanged.CollectionChanged{add{_h2943838991+=value;}remove{_h2943838991-=value;}}
        
        public MusicCollection()
        {
            this._blm3642925835 = new CodeFluent.Runtime.Utilities.BindingListManager<SoundSynchro.Music>(this);
        }
        
        public MusicCollection(SoundSynchro.Playlist musicsPlaylistPlaylist)
        {
            this._blm3642925835 = new CodeFluent.Runtime.Utilities.BindingListManager<SoundSynchro.Music>(this);
            this._musicsPlaylistPlaylist = musicsPlaylistPlaylist;
        }
        
        [System.ComponentModel.BrowsableAttribute(false)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public virtual bool RaisePropertyChangedEvents
        {
            get
            {
                return this._raisePropertyChangedEvents;
            }
            set
            {
                this._raisePropertyChangedEvents = value;
            }
        }
        
        public virtual bool RaiseCollectionChangedEvents
        {
            get
            {
                return this._raiseCollectionChangedEvents;
            }
            set
            {
                this._raiseCollectionChangedEvents = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        protected System.Collections.Generic.List<SoundSynchro.Music> BaseList
        {
            get
            {
                return this._baseList;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        protected System.Collections.Generic.Dictionary<System.Guid, SoundSynchro.Music> BaseTable
        {
            get
            {
                return this._baseTable;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        System.Collections.IDictionary CodeFluent.Runtime.ICodeFluentSet.Relations
        {
            get
            {
                return this._relations;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=false)]
        public virtual int MaxCount
        {
            get
            {
                return this._maxCount;
            }
            set
            {
                this._maxCount = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public SoundSynchro.Playlist musicsPlaylistPlaylist
        {
            get
            {
                return this._musicsPlaylistPlaylist;
            }
        }
        
        public SoundSynchro.Music this[int index]
        {
            get
            {
                return ((SoundSynchro.Music)(this.BaseList[index]));
            }
            set
            {
                this.BaseList[index] = value;
            }
        }
        
        object System.Collections.IList.this[int index]
        {
            get
            {
                object i = this.BaseList[index];
                return i;
            }
            set
            {
                this.BaseList[index] = ((SoundSynchro.Music)(value));
            }
        }
        
        public SoundSynchro.Music this[System.Guid id]
        {
            get
            {
                if ((id.Equals(CodeFluentPersistence.DefaultGuidValue) == true))
                {
                    throw new System.ArgumentNullException("id");
                }
                SoundSynchro.Music i = this.TryGetValue(id);
                return i;
            }
            set
            {
                if ((id.Equals(CodeFluentPersistence.DefaultGuidValue) == true))
                {
                    throw new System.ArgumentNullException("id");
                }
                if ((value == null))
                {
                    SoundSynchro.Music music = this.TryGetValue(id);
                    if ((music != null))
                    {
                        this.Remove(music);
                    }
                    return;
                }
                SoundSynchro.Music existing = this.TryGetValue(value.id);
                if ((existing != null))
                {
                    this.Remove(existing);
                }
                this.Add(value);
            }
        }
        
        public virtual int Count
        {
            get
            {
                int v = ((System.Collections.IList)(this.BaseList)).Count;
                return v;
            }
        }
        
        public virtual bool IsSynchronized
        {
            get
            {
                bool v = ((System.Collections.IList)(this.BaseList)).IsSynchronized;
                return v;
            }
        }
        
        public virtual object SyncRoot
        {
            get
            {
                object v = ((System.Collections.IList)(this.BaseList)).SyncRoot;
                return v;
            }
        }
        
        public virtual bool IsFixedSize
        {
            get
            {
                bool v = ((System.Collections.IList)(this.BaseList)).IsFixedSize;
                return v;
            }
        }
        
        public virtual bool IsReadOnly
        {
            get
            {
                bool v = ((System.Collections.IList)(this.BaseList)).IsReadOnly;
                return v;
            }
        }
        
        public virtual bool RaiseListChangedEvents
        {
            get
            {
                return this._raiseListChangedEvents;
            }
            set
            {
                this._raiseListChangedEvents = value;
            }
        }
        
        bool System.ComponentModel.IBindingList.AllowEdit
        {
            get
            {
                return this._blm3642925835.AllowEdit;
            }
        }
        
        bool System.ComponentModel.IBindingList.AllowNew
        {
            get
            {
                return this._blm3642925835.AllowNew;
            }
        }
        
        bool System.ComponentModel.IBindingList.AllowRemove
        {
            get
            {
                return this._blm3642925835.AllowRemove;
            }
        }
        
        bool System.ComponentModel.IBindingList.IsSorted
        {
            get
            {
                return this._blm3642925835.IsSorted;
            }
        }
        
        System.ComponentModel.ListSortDirection System.ComponentModel.IBindingList.SortDirection
        {
            get
            {
                return this._blm3642925835.SortDirection;
            }
        }
        
        System.ComponentModel.PropertyDescriptor System.ComponentModel.IBindingList.SortProperty
        {
            get
            {
                return this._blm3642925835.SortProperty;
            }
        }
        
        bool System.ComponentModel.IBindingList.SupportsChangeNotification
        {
            get
            {
                return true;
            }
        }
        
        bool System.ComponentModel.IBindingList.SupportsSearching
        {
            get
            {
                return this._blm3642925835.SupportsSearching;
            }
        }
        
        bool System.ComponentModel.IBindingList.SupportsSorting
        {
            get
            {
                return this._blm3642925835.SupportsSorting;
            }
        }
        
        bool System.ComponentModel.IRaiseItemChangedEvents.RaisesItemChangedEvents
        {
            get
            {
                return this.RaiseListChangedEvents;
            }
        }
        
        [field:System.NonSerializedAttribute()]
        public event System.ComponentModel.CollectionChangeEventHandler CollectionChanged;
        
        [field:System.NonSerializedAttribute()]
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        [field:System.NonSerializedAttribute()]
        public event System.ComponentModel.AddingNewEventHandler AddingNew;
        
        [field:System.NonSerializedAttribute()]
        public event System.ComponentModel.ListChangedEventHandler ListChanged;
        
        protected virtual void OnPropertyChanged(System.ComponentModel.PropertyChangedEventArgs e)
        {
            if ((this.RaisePropertyChangedEvents == false))
            {
                return;
            }
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, e);
            }
        }
        
        protected virtual void OnCollectionChanged(System.ComponentModel.CollectionChangeEventArgs e)
        {
            if ((this.RaiseCollectionChangedEvents == false))
            {
                return;
            }
            if ((this.CollectionChanged != null))
            {
                this.CollectionChanged(this, e);
            }
            CodeFluent.Runtime.ServiceModel.CollectionChangeNotifier.Notify(this, e, this._h2943838991);
            this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("Count"));
            this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("Item[]"));
        }
        
        protected virtual void Relate(SoundSynchro.Music item, CodeFluent.Runtime.CodeFluentRelationType relationType)
        {
            ((CodeFluent.Runtime.ICodeFluentSet)(this)).Relations[item] = relationType;
        }
        
        public int Add(SoundSynchro.Music music)
        {
            int localAdd = this.BaseList.Count;
            this.BaseAdd(music);
            return localAdd;
        }
        
        protected virtual int BaseAdd(SoundSynchro.Music music)
        {
            if ((music == null))
            {
                throw new System.ArgumentNullException("music");
            }
            if ((music.id.Equals(CodeFluentPersistence.DefaultGuidValue) == true))
            {
                CodeFluent.Runtime.CodeFluentRuntimeException.Throw("invalidEntityKey", "id", "music", "SoundSynchro.Music");
            }
            try
            {
                this.BaseTable.Add(music.id, music);
            }
            catch (System.ArgumentNullException ane)
            {
                throw new System.ArgumentNullException(SoundSynchro.Resources.Manager.GetUserMessage(null, CodeFluent.Runtime.UserExceptionType.VoidCollectionKey, "SoundSynchro.MusicCollection", music.EntityKey), ane);
            }
            catch (System.ArgumentException ae)
            {
                throw new System.ArgumentException(SoundSynchro.Resources.Manager.GetUserMessage(null, CodeFluent.Runtime.UserExceptionType.ItemAlreadyAdded, "SoundSynchro.MusicCollection", music.id), ae);
            }
            music.KeyChanged += new System.EventHandler<CodeFluent.Runtime.Utilities.KeyChangedEventArgs<System.Guid>>(this.OnItemKeyChanged);
            this.Relate(music, CodeFluent.Runtime.CodeFluentRelationType.Added);
            if ((this._musicsPlaylistPlaylist != null))
            {
                this._musicsPlaylistPlaylist.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified;
            }
            int localAdd = this.BaseList.Count;
            this.BaseList.Add(music);
            this.OnCollectionChanged(new CodeFluent.Runtime.Utilities.IndexedCollectionChangeEventArgs(System.ComponentModel.CollectionChangeAction.Add, music, localAdd));
            this.OnListChanged(new System.ComponentModel.ListChangedEventArgs(System.ComponentModel.ListChangedType.ItemAdded, localAdd));
            return localAdd;
        }
        
        int System.Collections.IList.Add(object value)
        {
            SoundSynchro.Music music = null;
            try
            {
                music = ((SoundSynchro.Music)(value));
            }
            catch (System.InvalidCastException )
            {
                string key = null;
                try
                {
                    key = ((string)(value));
                    int count = this.Count;
                    if ((this.AddByEntityKey(key) != null))
                    {
                        return 1;
                    }
                    return 0;
                }
                catch (System.InvalidCastException )
                {
                }
                if ((key == null))
                {
                    throw new System.ArgumentException("value");
                }
            }
            if ((music == null))
            {
                throw new System.ArgumentException("value");
            }
            int localAdd = this.Add(music);
            return localAdd;
        }
        
        void System.Collections.Generic.ICollection<SoundSynchro.Music>.Add(SoundSynchro.Music music)
        {
            this.BaseAdd(music);
        }
        
        public virtual SoundSynchro.Music AddByEntityKey(string key)
        {
            SoundSynchro.Music music = SoundSynchro.Music.LoadByEntityKey(key);
            if (((music != null) 
                        && (this.Contains(music) == false)))
            {
                this.Add(music);
            }
            return music;
        }
        
        public void Sort()
        {
            this.Sort(null);
        }
        
        public virtual void Sort(System.Collections.Generic.IComparer<SoundSynchro.Music> comparer)
        {
            this.BaseList.Sort(comparer);
        }
        
        public void CopyTo(SoundSynchro.Music[] array, int index)
        {
            this.BaseCopyTo(array, index);
        }
        
        protected virtual void BaseCopyTo(SoundSynchro.Music[] array, int index)
        {
            this.BaseList.CopyTo(array, index);
        }
        
        void System.Collections.ICollection.CopyTo(System.Array array, int index)
        {
            CodeFluent.Runtime.Utilities.ConvertUtilities.CopyTo(this, array, index);
        }
        
        public bool Contains(SoundSynchro.Music music)
        {
            bool localContains = this.BaseContains(music);
            return localContains;
        }
        
        protected virtual bool BaseContains(SoundSynchro.Music music)
        {
            if ((music == null))
            {
                return false;
            }
            bool localContains = this.BaseTable.ContainsKey(music.id);
            return localContains;
        }
        
        bool System.Collections.IList.Contains(object value)
        {
            SoundSynchro.Music music;
			music = value as SoundSynchro.Music;
            return this.Contains(music);
        }
        
        public int IndexOf(SoundSynchro.Music music)
        {
            int localIndexOf = this.BaseIndexOf(music);
            return localIndexOf;
        }
        
        protected virtual int BaseIndexOf(SoundSynchro.Music music)
        {
            if ((music == null))
            {
                return -1;
            }
            int localIndexOf = this.BaseList.IndexOf(music);
            return localIndexOf;
        }
        
        int System.Collections.IList.IndexOf(object value)
        {
            SoundSynchro.Music music;
			music = value as SoundSynchro.Music;
            return this.IndexOf(music);
        }
        
        public void Insert(int index, SoundSynchro.Music music)
        {
            this.BaseInsert(index, music);
        }
        
        protected virtual void BaseInsert(int index, SoundSynchro.Music music)
        {
            if ((music == null))
            {
                throw new System.ArgumentNullException("music");
            }
            try
            {
                this.BaseTable.Add(music.id, music);
            }
            catch (System.ArgumentNullException ane)
            {
                throw new System.ArgumentNullException(SoundSynchro.Resources.Manager.GetUserMessage(null, CodeFluent.Runtime.UserExceptionType.VoidCollectionKey, "SoundSynchro.MusicCollection", music.EntityKey), ane);
            }
            catch (System.ArgumentException ae)
            {
                throw new System.ArgumentException(SoundSynchro.Resources.Manager.GetUserMessage(null, CodeFluent.Runtime.UserExceptionType.ItemAlreadyAdded, "SoundSynchro.MusicCollection", music.id), ae);
            }
            this.BaseList.Insert(index, music);
            this.Relate(music, CodeFluent.Runtime.CodeFluentRelationType.Added);
            if ((this._musicsPlaylistPlaylist != null))
            {
                this._musicsPlaylistPlaylist.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified;
            }
            this.OnCollectionChanged(new CodeFluent.Runtime.Utilities.IndexedCollectionChangeEventArgs(System.ComponentModel.CollectionChangeAction.Add, music, index));
            this.OnListChanged(new System.ComponentModel.ListChangedEventArgs(System.ComponentModel.ListChangedType.ItemAdded, index));
        }
        
        void System.Collections.IList.Insert(int index, object value)
        {
            SoundSynchro.Music music;
			music = value as SoundSynchro.Music;
            this.Insert(index, music);
        }
        
        public virtual void Clear()
        {
            int index;
            int count = this.Count;
            for (index = 0; (index < count); index = (index + 1))
            {
                SoundSynchro.Music Music = this[0];
                this.BaseRemove(Music);
            }
            this.OnCollectionChanged(new CodeFluent.Runtime.Utilities.IndexedCollectionChangeEventArgs(System.ComponentModel.CollectionChangeAction.Refresh, null));
            this.OnListChanged(new System.ComponentModel.ListChangedEventArgs(System.ComponentModel.ListChangedType.Reset, -1));
        }
        
        public bool Remove(SoundSynchro.Music music)
        {
            return this.BaseRemove(music);
        }
        
        protected virtual bool BaseRemove(SoundSynchro.Music music)
        {
            if ((music == null))
            {
                throw new System.ArgumentNullException("music");
            }
            int index = this.IndexOf(music);
            this.OnListChanged(new System.ComponentModel.ListChangedEventArgs(((System.ComponentModel.ListChangedType)(CodeFluent.Runtime.Utilities.SortableBindingList<SoundSynchro.Music>.ListChangedTypeDeleting)), index));
            bool ret;
            ret = this.BaseList.Remove(music);
            music.KeyChanged -= new System.EventHandler<CodeFluent.Runtime.Utilities.KeyChangedEventArgs<System.Guid>>(this.OnItemKeyChanged);
            ret = this.BaseTable.Remove(music.id);
            this.Relate(music, CodeFluent.Runtime.CodeFluentRelationType.Removed);
            if ((this._musicsPlaylistPlaylist != null))
            {
                this._musicsPlaylistPlaylist.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified;
            }
            this.OnCollectionChanged(new CodeFluent.Runtime.Utilities.IndexedCollectionChangeEventArgs(System.ComponentModel.CollectionChangeAction.Remove, music, index));
            this.OnListChanged(new System.ComponentModel.ListChangedEventArgs(System.ComponentModel.ListChangedType.ItemDeleted, index));
            return ret;
        }
        
        void System.Collections.IList.Remove(object value)
        {
            SoundSynchro.Music music;
			music = value as SoundSynchro.Music;
            this.Remove(music);
        }
        
        public virtual void RemoveAt(int index)
        {
            this.OnListChanged(new System.ComponentModel.ListChangedEventArgs(((System.ComponentModel.ListChangedType)(CodeFluent.Runtime.Utilities.SortableBindingList<SoundSynchro.Music>.ListChangedTypeDeleting)), index));
            SoundSynchro.Music music = this.BaseList[index];
            if ((music != null))
            {
                music.KeyChanged -= new System.EventHandler<CodeFluent.Runtime.Utilities.KeyChangedEventArgs<System.Guid>>(this.OnItemKeyChanged);
                this.BaseTable.Remove(music.id);
                this.Relate(music, CodeFluent.Runtime.CodeFluentRelationType.Removed);
            }
            if ((this._musicsPlaylistPlaylist != null))
            {
                this._musicsPlaylistPlaylist.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified;
            }
            this.BaseList.RemoveAt(index);
            this.OnCollectionChanged(new CodeFluent.Runtime.Utilities.IndexedCollectionChangeEventArgs(System.ComponentModel.CollectionChangeAction.Remove, music, index));
            this.OnListChanged(new System.ComponentModel.ListChangedEventArgs(System.ComponentModel.ListChangedType.ItemDeleted, index));
        }
        
        public virtual System.Collections.Generic.IEnumerator<SoundSynchro.Music> GetEnumerator()
        {
            System.Collections.Generic.IEnumerator<SoundSynchro.Music> e = this.BaseList.GetEnumerator();
            return e;
        }
        
        System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator()
        {
            return this.BaseList.GetEnumerator();
        }
        
        private SoundSynchro.Music TryGetValue(System.Guid key)
        {
            SoundSynchro.Music music;
            if ((this.BaseTable.TryGetValue(key, out music) == true))
            {
                return music;
            }
            return null;
        }
        
        public virtual void SaveAll()
        {
            int index;
            for (index = (this.Count - 1); (index >= 0); index = (index - 1))
            {
                SoundSynchro.Music music = this[index];
                music.Save();
                if ((music.EntityState == CodeFluent.Runtime.CodeFluentEntityState.Deleted))
                {
                    this.Remove(music);
                }
            }
        }
        
        private void LoadAll(int pageIndex, int pageSize, CodeFluent.Runtime.PageOptions pageOptions, System.Data.IDataReader reader)
        {
            if ((reader == null))
            {
                throw new System.ArgumentNullException("reader");
            }
            if ((pageIndex < 0))
            {
                pageIndex = 0;
            }
            if ((pageSize < 0))
            {
                if ((pageOptions != null))
                {
                    pageSize = pageOptions.DefaultPageSize;
                }
                else
                {
                    pageSize = int.MaxValue;
                }
            }
            this._musicsPlaylistPlaylist = null;
            this.BaseList.Clear();
            this.BaseTable.Clear();
            int count = 0;
            int readCount = 0;
            bool readerRead;
            for (readerRead = reader.Read(); ((readerRead == true) 
                        && ((count < this.MaxCount) 
                        && (count < pageSize))); readerRead = reader.Read())
            {
                readCount = (readCount + 1);
                if ((CodeFluent.Runtime.CodeFluentPersistence.CanAddEntity(pageIndex, pageSize, pageOptions, readCount) == true))
                {
                    SoundSynchro.Music music = new SoundSynchro.Music();
                    ((CodeFluent.Runtime.ICodeFluentEntity)(music)).ReadRecord(reader);
                    if ((this.BaseContains(music) == false))
                    {
                        this.BaseAdd(music);
                        count = (count + 1);
                    }
                    music.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Unchanged;
                }
            }
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, true)]
        public static SoundSynchro.MusicCollection PageLoadAll(int pageIndex, int pageSize, CodeFluent.Runtime.PageOptions pageOptions)
        {
            if ((pageIndex < 0))
            {
                pageIndex = 0;
            }
            if ((pageSize < 0))
            {
                if ((pageOptions != null))
                {
                    pageSize = pageOptions.DefaultPageSize;
                }
                else
                {
                    pageSize = int.MaxValue;
                }
            }
            SoundSynchro.MusicCollection ret = new SoundSynchro.MusicCollection();
            System.Data.IDataReader reader = null;
            try
            {
                reader = SoundSynchro.MusicCollection.PageDataLoadAll(pageOptions);
                if ((reader == null))
                {
                    return ret;
                }
                ret.LoadAll(pageIndex, pageSize, pageOptions, reader);
            }
            finally
            {
                if ((reader != null))
                {
                    reader.Dispose();
                }
                CodeFluent.Runtime.CodeFluentPersistence.CompleteCommand(SoundSynchro.Constants.SoundSynchroStoreName);
            }
            return ret;
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, true)]
        public static SoundSynchro.MusicCollection LoadAll()
        {
            SoundSynchro.MusicCollection ret = SoundSynchro.MusicCollection.PageLoadAll(int.MinValue, int.MaxValue, null);
            return ret;
        }
        
        public static System.Data.IDataReader PageDataLoadAll(CodeFluent.Runtime.PageOptions pageOptions)
        {
            CodeFluent.Runtime.CodeFluentPersistence persistence = CodeFluentContext.Get(SoundSynchro.Constants.SoundSynchroStoreName).Persistence;
            persistence.CreateStoredProcedureCommand(null, "Music", "LoadAll");
            if ((pageOptions != null))
            {
                System.Collections.IEnumerator enumerator = pageOptions.OrderByArguments.GetEnumerator();
                bool b;
                int index = 0;
                for (b = enumerator.MoveNext(); b; b = enumerator.MoveNext())
                {
                    CodeFluent.Runtime.OrderByArgument argument = ((CodeFluent.Runtime.OrderByArgument)(enumerator.Current));
                    persistence.AddParameter(string.Format("@_orderBy{0}", index), argument.Name);
                    persistence.AddParameter(string.Format("@_orderByDirection{0}", index), ((int)(argument.Direction)));
                    index = (index + 1);
                }
            }
            System.Data.IDataReader reader = CodeFluentContext.Get(SoundSynchro.Constants.SoundSynchroStoreName).Persistence.ExecuteReader();
            return reader;
        }
        
        public static System.Data.IDataReader DataLoadAll()
        {
            System.Data.IDataReader reader = SoundSynchro.MusicCollection.PageDataLoadAll(null);
            return reader;
        }
        
        private void LoadmusicsByPlaylist(int pageIndex, int pageSize, CodeFluent.Runtime.PageOptions pageOptions, System.Data.IDataReader reader, SoundSynchro.Playlist playlist)
        {
            if ((reader == null))
            {
                throw new System.ArgumentNullException("reader");
            }
            if ((pageIndex < 0))
            {
                pageIndex = 0;
            }
            if ((pageSize < 0))
            {
                if ((pageOptions != null))
                {
                    pageSize = pageOptions.DefaultPageSize;
                }
                else
                {
                    pageSize = int.MaxValue;
                }
            }
            CodeFluent.Runtime.CodeFluentEntityState playlistState = CodeFluent.Runtime.CodeFluentEntityState.Unchanged;
            if ((playlist != null))
            {
                playlistState = playlist.EntityState;
            }
            this._musicsPlaylistPlaylist = playlist;
            this.BaseList.Clear();
            this.BaseTable.Clear();
            int count = 0;
            int readCount = 0;
            bool readerRead;
            for (readerRead = reader.Read(); ((readerRead == true) 
                        && ((count < this.MaxCount) 
                        && (count < pageSize))); readerRead = reader.Read())
            {
                readCount = (readCount + 1);
                if ((CodeFluent.Runtime.CodeFluentPersistence.CanAddEntity(pageIndex, pageSize, pageOptions, readCount) == true))
                {
                    SoundSynchro.Music music = new SoundSynchro.Music();
                    ((CodeFluent.Runtime.ICodeFluentEntity)(music)).ReadRecord(reader);
                    if ((this.BaseContains(music) == false))
                    {
                        this.BaseAdd(music);
                        count = (count + 1);
                    }
                    music.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Unchanged;
                }
            }
            if ((playlist != null))
            {
                playlist.EntityState = playlistState;
            }
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, true)]
        public static SoundSynchro.MusicCollection PageLoadmusicsByPlaylist(int pageIndex, int pageSize, CodeFluent.Runtime.PageOptions pageOptions, SoundSynchro.Playlist playlist)
        {
            if ((pageIndex < 0))
            {
                pageIndex = 0;
            }
            if ((pageSize < 0))
            {
                if ((pageOptions != null))
                {
                    pageSize = pageOptions.DefaultPageSize;
                }
                else
                {
                    pageSize = int.MaxValue;
                }
            }
            SoundSynchro.MusicCollection ret = new SoundSynchro.MusicCollection();
            System.Data.IDataReader reader = null;
            try
            {
                reader = SoundSynchro.MusicCollection.PageDataLoadmusicsByPlaylist(pageOptions, playlist);
                if ((reader == null))
                {
                    return ret;
                }
                ret.LoadmusicsByPlaylist(pageIndex, pageSize, pageOptions, reader, playlist);
            }
            finally
            {
                if ((reader != null))
                {
                    reader.Dispose();
                }
                CodeFluent.Runtime.CodeFluentPersistence.CompleteCommand(SoundSynchro.Constants.SoundSynchroStoreName);
            }
            return ret;
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, true)]
        public static SoundSynchro.MusicCollection LoadmusicsByPlaylist(SoundSynchro.Playlist playlist)
        {
            SoundSynchro.MusicCollection ret = SoundSynchro.MusicCollection.PageLoadmusicsByPlaylist(int.MinValue, int.MaxValue, null, playlist);
            return ret;
        }
        
        public static System.Data.IDataReader PageDataLoadmusicsByPlaylist(CodeFluent.Runtime.PageOptions pageOptions, SoundSynchro.Playlist playlist)
        {
            if ((playlist == null))
            {
                return null;
            }
            if ((playlist.id.Equals(CodeFluentPersistence.DefaultGuidValue) == true))
            {
                CodeFluent.Runtime.CodeFluentRuntimeException.Throw("invalidEntityKey", "id", "playlist", "SoundSynchro.Playlist");
            }
            CodeFluent.Runtime.CodeFluentPersistence persistence = CodeFluentContext.Get(SoundSynchro.Constants.SoundSynchroStoreName).Persistence;
            persistence.CreateStoredProcedureCommand(null, "Music", "LoadmusicsByPlaylist");
            persistence.AddParameter("@Playlistid", playlist.id, CodeFluentPersistence.DefaultGuidValue);
            if ((pageOptions != null))
            {
                System.Collections.IEnumerator enumerator = pageOptions.OrderByArguments.GetEnumerator();
                bool b;
                int index = 0;
                for (b = enumerator.MoveNext(); b; b = enumerator.MoveNext())
                {
                    CodeFluent.Runtime.OrderByArgument argument = ((CodeFluent.Runtime.OrderByArgument)(enumerator.Current));
                    persistence.AddParameter(string.Format("@_orderBy{0}", index), argument.Name);
                    persistence.AddParameter(string.Format("@_orderByDirection{0}", index), ((int)(argument.Direction)));
                    index = (index + 1);
                }
            }
            System.Data.IDataReader reader = CodeFluentContext.Get(SoundSynchro.Constants.SoundSynchroStoreName).Persistence.ExecuteReader();
            return reader;
        }
        
        public static System.Data.IDataReader DataLoadmusicsByPlaylist(SoundSynchro.Playlist playlist)
        {
            System.Data.IDataReader reader = SoundSynchro.MusicCollection.PageDataLoadmusicsByPlaylist(null, playlist);
            return reader;
        }
        
        private void SearchAll(int pageIndex, int pageSize, CodeFluent.Runtime.PageOptions pageOptions, System.Data.IDataReader reader, string s)
        {
            if ((reader == null))
            {
                throw new System.ArgumentNullException("reader");
            }
            if ((pageIndex < 0))
            {
                pageIndex = 0;
            }
            if ((pageSize < 0))
            {
                if ((pageOptions != null))
                {
                    pageSize = pageOptions.DefaultPageSize;
                }
                else
                {
                    pageSize = int.MaxValue;
                }
            }
            this._musicsPlaylistPlaylist = null;
            this.BaseList.Clear();
            this.BaseTable.Clear();
            int count = 0;
            int readCount = 0;
            bool readerRead;
            for (readerRead = reader.Read(); ((readerRead == true) 
                        && ((count < this.MaxCount) 
                        && (count < pageSize))); readerRead = reader.Read())
            {
                readCount = (readCount + 1);
                if ((CodeFluent.Runtime.CodeFluentPersistence.CanAddEntity(pageIndex, pageSize, pageOptions, readCount) == true))
                {
                    SoundSynchro.Music music = new SoundSynchro.Music();
                    ((CodeFluent.Runtime.ICodeFluentEntity)(music)).ReadRecord(reader);
                    if ((this.BaseContains(music) == false))
                    {
                        this.BaseAdd(music);
                        count = (count + 1);
                    }
                    music.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Unchanged;
                }
            }
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, true)]
        public static SoundSynchro.MusicCollection PageSearchAll(int pageIndex, int pageSize, CodeFluent.Runtime.PageOptions pageOptions, string s)
        {
            if ((pageIndex < 0))
            {
                pageIndex = 0;
            }
            if ((pageSize < 0))
            {
                if ((pageOptions != null))
                {
                    pageSize = pageOptions.DefaultPageSize;
                }
                else
                {
                    pageSize = int.MaxValue;
                }
            }
            SoundSynchro.MusicCollection ret = new SoundSynchro.MusicCollection();
            System.Data.IDataReader reader = null;
            try
            {
                reader = SoundSynchro.MusicCollection.PageDataSearchAll(pageOptions, s);
                if ((reader == null))
                {
                    return ret;
                }
                ret.SearchAll(pageIndex, pageSize, pageOptions, reader, s);
            }
            finally
            {
                if ((reader != null))
                {
                    reader.Dispose();
                }
                CodeFluent.Runtime.CodeFluentPersistence.CompleteCommand(SoundSynchro.Constants.SoundSynchroStoreName);
            }
            return ret;
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, true)]
        public static SoundSynchro.MusicCollection SearchAll(string s)
        {
            SoundSynchro.MusicCollection ret = SoundSynchro.MusicCollection.PageSearchAll(int.MinValue, int.MaxValue, null, s);
            return ret;
        }
        
        public static System.Data.IDataReader PageDataSearchAll(CodeFluent.Runtime.PageOptions pageOptions, string s)
        {
            if ((s == default(string)))
            {
                throw new System.ArgumentNullException("s");
            }
            CodeFluent.Runtime.CodeFluentPersistence persistence = CodeFluentContext.Get(SoundSynchro.Constants.SoundSynchroStoreName).Persistence;
            persistence.CreateStoredProcedureCommand(null, "Music", "SearchAll");
            persistence.AddParameter("@s", s);
            if ((pageOptions != null))
            {
                System.Collections.IEnumerator enumerator = pageOptions.OrderByArguments.GetEnumerator();
                bool b;
                int index = 0;
                for (b = enumerator.MoveNext(); b; b = enumerator.MoveNext())
                {
                    CodeFluent.Runtime.OrderByArgument argument = ((CodeFluent.Runtime.OrderByArgument)(enumerator.Current));
                    persistence.AddParameter(string.Format("@_orderBy{0}", index), argument.Name);
                    persistence.AddParameter(string.Format("@_orderByDirection{0}", index), ((int)(argument.Direction)));
                    index = (index + 1);
                }
            }
            System.Data.IDataReader reader = CodeFluentContext.Get(SoundSynchro.Constants.SoundSynchroStoreName).Persistence.ExecuteReader();
            return reader;
        }
        
        public static System.Data.IDataReader DataSearchAll(string s)
        {
            System.Data.IDataReader reader = SoundSynchro.MusicCollection.PageDataSearchAll(null, s);
            return reader;
        }
        
        protected virtual void BaseTrace(System.CodeDom.Compiler.IndentedTextWriter writer)
        {
            writer.Write("[");
            writer.Write(string.Concat("Count=", this.Count));
            writer.Write("]");
        }
        
        public string Trace()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            System.IO.StringWriter stringWriter = new System.IO.StringWriter(stringBuilder, System.Globalization.CultureInfo.CurrentCulture);
            System.CodeDom.Compiler.IndentedTextWriter writer = new System.CodeDom.Compiler.IndentedTextWriter(stringWriter);
            this.BaseTrace(writer);
            writer.Flush();
            ((System.IDisposable)(writer)).Dispose();
            ((System.IDisposable)(stringWriter)).Dispose();
            string sr = stringBuilder.ToString();
            return sr;
        }
        
        void CodeFluent.Runtime.ICodeFluentObject.Trace(System.CodeDom.Compiler.IndentedTextWriter writer)
        {
            this.BaseTrace(writer);
        }
        
        public virtual void CopyTo(SoundSynchro.MusicCollection collection, bool deep)
        {
            if ((typeof(System.ICloneable).IsAssignableFrom(typeof(SoundSynchro.Music)) == false))
            {
                deep = false;
            }
            System.Collections.Generic.IEnumerator<SoundSynchro.Music> enumerator = this.GetEnumerator();
            bool b;
            for (b = enumerator.MoveNext(); b; b = enumerator.MoveNext())
            {
                if ((deep == true))
                {
                    collection.Add(((SoundSynchro.Music)(((System.ICloneable)(enumerator.Current)).Clone())));
                }
                else
                {
                    collection.Add(enumerator.Current);
                }
            }
        }
        
        public virtual SoundSynchro.MusicCollection Clone(bool deep)
        {
            SoundSynchro.MusicCollection ret = new SoundSynchro.MusicCollection();
            this.CopyTo(ret, deep);
            return ret;
        }
        
        object System.ICloneable.Clone()
        {
            return this.Clone(true);
        }
        
        public virtual void CancelNew(int index)
        {
            if (((this._addNewPos >= 0) 
                        && (this._addNewPos == index)))
            {
                this.RemoveAt(index);
                this._addNewPos = -1;
            }
        }
        
        public virtual void EndNew(int index)
        {
            if (((this._addNewPos >= 0) 
                        && (this._addNewPos == index)))
            {
                this._addNewPos = -1;
            }
        }
        
        void System.ComponentModel.IBindingList.AddIndex(System.ComponentModel.PropertyDescriptor property)
        {
            this._blm3642925835.AddIndex(property);
        }
        
        protected virtual void OnAddingNew(System.ComponentModel.AddingNewEventArgs e)
        {
            if ((this.AddingNew != null))
            {
                this.AddingNew(this, e);
            }
        }
        
        object System.ComponentModel.IBindingList.AddNew()
        {
            SoundSynchro.Music add = new SoundSynchro.Music();
            System.ComponentModel.AddingNewEventArgs e = new System.ComponentModel.AddingNewEventArgs(add);
            this.OnAddingNew(e);
            add = ((SoundSynchro.Music)(e.NewObject));
            if ((add == null))
            {
                add = new SoundSynchro.Music();
            }
            add.id = System.Guid.NewGuid();
            this._addNewPos = this.Add(add);
            return add;
        }
        
        void System.ComponentModel.IBindingList.ApplySort(System.ComponentModel.PropertyDescriptor property, System.ComponentModel.ListSortDirection direction)
        {
            this._blm3642925835.ApplySort(property, direction);
        }
        
        int System.ComponentModel.IBindingList.Find(System.ComponentModel.PropertyDescriptor property, object key)
        {
            return this._blm3642925835.Find(property, key);
        }
        
        void System.ComponentModel.IBindingList.RemoveIndex(System.ComponentModel.PropertyDescriptor property)
        {
            this._blm3642925835.RemoveIndex(property);
        }
        
        void System.ComponentModel.IBindingList.RemoveSort()
        {
            this._blm3642925835.RemoveSort();
        }
        
        protected virtual void OnListChanged(System.ComponentModel.ListChangedEventArgs e)
        {
            if ((e == null))
            {
                throw new System.ArgumentNullException("e");
            }
            if ((this.RaiseListChangedEvents == false))
            {
                return;
            }
            if ((((e.ListChangedType == System.ComponentModel.ListChangedType.Reset) 
                        == false) 
                        && (e.NewIndex < 0)))
            {
                return;
            }
            if ((this.ListChanged != null))
            {
                this.ListChanged(this, e);
            }
        }
        
        public void AddRange(System.Collections.Generic.IEnumerable<SoundSynchro.Music> collection)
        {
            CodeFluent.Runtime.Utilities.ConvertUtilities.AddRange(this, collection);
        }
        
        private void OnItemKeyChanged(object sender, CodeFluent.Runtime.Utilities.KeyChangedEventArgs<System.Guid> e)
        {
            if ((e == null))
            {
                throw new System.ArgumentNullException("e");
            }
            SoundSynchro.Music existing;
            if ((this.BaseTable.TryGetValue(e.OldKey, out existing) == false))
            {
                return;
            }
            if (((sender != null) 
                        && (typeof(CodeFluent.Runtime.Utilities.IKeyable<System.Guid>).IsAssignableFrom(sender.GetType()) == true)))
            {
                CodeFluent.Runtime.Utilities.IKeyable<System.Guid> item = ((CodeFluent.Runtime.Utilities.IKeyable<System.Guid>)(sender));
                try
                {
                    this.BaseTable.Add(item.Key, existing);
                }
                catch (System.ArgumentNullException ane)
                {
                    throw new System.ArgumentNullException(SoundSynchro.Resources.Manager.GetUserMessage(null, CodeFluent.Runtime.UserExceptionType.VoidCollectionKey, "SoundSynchro.MusicCollection", ((CodeFluent.Runtime.ICodeFluentEntity)(item)).EntityKey), ane);
                }
                catch (System.ArgumentException ae)
                {
                    throw new System.ArgumentException(SoundSynchro.Resources.Manager.GetUserMessage(null, CodeFluent.Runtime.UserExceptionType.ItemAlreadyAdded, "SoundSynchro.MusicCollection", item.Key), ae);
                }
                this.BaseTable.Remove(e.OldKey);
            }
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, true)]
        public static SoundSynchro.MusicCollection PageLoadAll(int pageIndex, int pageSize)
        {
            return SoundSynchro.MusicCollection.PageLoadAll(pageIndex, pageSize, null);
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, true)]
        public static SoundSynchro.MusicCollection PageLoadmusicsByPlaylist(int pageIndex, int pageSize, System.Guid playlistId)
        {
            SoundSynchro.Playlist playlist = SoundSynchro.Playlist.Load(playlistId);
            if ((playlist == null))
            {
                return new SoundSynchro.MusicCollection();
            }
            return SoundSynchro.MusicCollection.PageLoadmusicsByPlaylist(pageIndex, pageSize, null, playlist);
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, true)]
        public static SoundSynchro.MusicCollection PageSearchAll(int pageIndex, int pageSize, string s)
        {
            return SoundSynchro.MusicCollection.PageSearchAll(pageIndex, pageSize, null, s);
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Update, true)]
        public static bool Save(SoundSynchro.Music music)
        {
            if ((music == null))
            {
                return false;
            }
            bool ret = music.Save();
            return ret;
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Insert, true)]
        public static bool Insert(SoundSynchro.Music music)
        {
            bool ret = SoundSynchro.Music.Save(music);
            return ret;
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Delete, true)]
        public static bool Delete(SoundSynchro.Music music)
        {
            if ((music == null))
            {
                return false;
            }
            bool ret = music.Delete();
            return ret;
        }
    }
}
